import { sitemapIds } from '@/lib/server/sitemap-entries';
import { createServerTransport } from '@/lib/server/transport';
import { absoluteUrl } from '@/lib/routes';
import { allPublicWaterKeys } from '../(site)/ape-publice/_server/source';

/*
 * /sitemap.xml — the sitemap index (sitemaps.org): one <sitemap> per group / chunk generated by
 * app/sitemaps/sitemap.ts (generateSitemaps). robots.txt points here.
 */

const escapeXml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export async function GET() {
  const ids = await sitemapIds(createServerTransport(), allPublicWaterKeys);
  const body = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...ids.map(id => `<sitemap><loc>${escapeXml(absoluteUrl(`/sitemaps/sitemap/${encodeURIComponent(id)}.xml`))}</loc></sitemap>`),
    '</sitemapindex>',
  ].join('\n');
  return new Response(body, { headers: { 'content-type': 'application/xml; charset=utf-8' } });
}
