/**
 * Server-time offset. fish `features/partide/domain/serverClock.ts`.
 *
 * Rod timers are absolute deadlines stamped by the CMS, so a device with a skewed clock would
 * render a different countdown than its teammates. `now()` is what timer rendering must use
 * instead of Date.now().
 *
 * fish kept the offset in module state and fed it from a global axios response interceptor. Here
 * the sampling is two pure functions (value in → offset out) plus a small `createServerClock()`
 * holder the caller owns — the transport (or whoever sees the response headers) calls
 * `noteHttpDate(res.headers)`; nothing in core/ hooks into requests globally.
 *
 * A sample is only valid at the instant it is RECEIVED. The Firestore projection's `serverNow`
 * field is stamped when the CMS BUILT the document and Firestore re-delivers an unchanged document
 * on every resubscribe — feeding it here rewound the clock by the projection's age. Only feed
 * this from something generated by the request in hand:
 *  - `noteServerNow` — a live response body field (the rods PATCH reply).
 *  - `noteHttpDate`  — a response's `Date` header, corrected by `Age`.
 */

/** Offset (server − device, ms) from a live `serverNow` ISO body field; null when unparseable. */
export function offsetFromServerNow(iso: string, deviceNow: number): number | null {
  const parsed = Date.parse(iso);
  if (Number.isNaN(parsed)) return null;
  return parsed - deviceNow;
}

/**
 * Offset (server − device, ms) from a response's `Date` + `Age` headers; null when the sample
 * must be dropped.
 *
 * `Age` is not optional politeness: an HTTP cache MUST NOT rewrite `Date`, it reports staleness in
 * `Age` instead. A Cloudflare HIT on a `/feed/*` GET hands us an origin timestamp that can be
 * minutes or hours old. So `Date` is corrected by `Age`, and a response whose `Age` is present but
 * unparseable is dropped rather than trusted at face value.
 */
export function offsetFromHttpDate(
  rawDate: string | null | undefined,
  rawAge: string | number | null | undefined,
  deviceNow: number
): number | null {
  if (typeof rawDate !== 'string') return null;
  const date = Date.parse(rawDate);
  if (Number.isNaN(date)) return null;
  let ageMs = 0;
  if (rawAge != null) {
    const age = Number(rawAge);
    if (!Number.isFinite(age) || age < 0) return null;
    ageMs = age * 1000;
  }
  return date + ageMs - deviceNow;
}

/** Reads `date`/`age` from a fetch `Headers` or a plain header record (axios-style, any case). */
export function readDateHeaders(headers: unknown): { date: string | null; age: string | null } {
  if (headers == null || typeof headers !== 'object') return { date: null, age: null };
  if (typeof (headers as Headers).get === 'function') {
    const h = headers as Headers;
    return { date: h.get('date'), age: h.get('age') };
  }
  const h = headers as Record<string, unknown>;
  const date = h.date ?? h.Date;
  const age = h.age ?? h.Age;
  return {
    date: typeof date === 'string' ? date : null,
    age: age == null ? null : String(age),
  };
}

export type ServerClock = {
  noteServerNow(iso: string): void;
  noteHttpDate(headers: unknown): void;
  /** Device clock corrected by the last sample. */
  now(): number;
  /**
   * Whether any live response has been sampled yet. Until then `now()` is the device clock, and a
   * countdown or an «Expirat» drawn from it is a guess — the UI labels it as syncing.
   */
  hasSample(): boolean;
  reset(): void;
};

export function createServerClock(deviceNow: () => number = () => Date.now()): ServerClock {
  let offsetMs = 0;
  let sampled = false;
  const apply = (offset: number | null) => {
    if (offset === null) return;
    // No ordering guard: two in-flight responses can resolve out of order and briefly apply the
    // older sample. Deadlines are absolute, so the worst case is a sub-second countdown flicker
    // that self-corrects on the next sample.
    offsetMs = offset;
    sampled = true;
  };
  return {
    noteServerNow: iso => apply(offsetFromServerNow(iso, deviceNow())),
    noteHttpDate: headers => {
      const { date, age } = readDateHeaders(headers);
      apply(offsetFromHttpDate(date, age, deviceNow()));
    },
    now: () => deviceNow() + offsetMs,
    hasSample: () => sampled,
    reset: () => {
      offsetMs = 0;
      sampled = false;
    },
  };
}
